branches:
  only:
  - master
language: python
python:
- 3.5
install:
- pip install -r requirements.txt --use-mirrors
script:
- make publish
notifications:
  email:
    on_success: always
    on_failure: always
git:
  submodules: false
env:
  global:
  - secure: "cjf5GfseON9KKv+wtfqpkm0Cm2xukMvWWBB1Oh1QquvsTr48+yDJqjRsORlceAHrOMaO4iV+SaPk4RETaihbfrdJlh3sse4a5lg8tEtM6OntgSypcmKRgy3w72mRe5CEoJ4A2R6QFgerHo6W1XHwTHYEVLwexPwiHDD3RzWATbo="
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - rm -rf plugins/pandoc_reader
after_success: bash deploy.sh

